-- do not edit; automatically generated by UU.AG

module CilAbsSyn where

import Data.Int -- 
-- AsmInput ----------------------------------------------------
type AsmInput = ( (String),(Exp))
-- AsmInputs ---------------------------------------------------
type AsmInputs = [(AsmInput)]
-- AsmOutput ---------------------------------------------------
type AsmOutput = ( (String),(Lval))
-- AsmOutputs --------------------------------------------------
type AsmOutputs = [(AsmOutput)]
-- AttrParam ---------------------------------------------------
data AttrParam = AAlignOf (CilType)
               | AAlignOfE (AttrParam)
               | AAlignOfS (TypeSig)
               | ABinOp (BinOp) (AttrParam) (AttrParam)
               | ACons (String) (AttrParams)
               | ADot (AttrParam) (String)
               | AInt (Int)
               | ASizeOf (CilType)
               | ASizeOfE (AttrParam)
               | ASizeOfS (TypeSig)
               | AStr (String)
               | AUnOp (UnOp) (AttrParam)
               deriving ( Show)
-- AttrParams --------------------------------------------------
type AttrParams = [(AttrParam)]
-- BinOp -------------------------------------------------------
data BinOp = BAnd 
           | BOr 
           | BXor 
           | Div 
           | Eq 
           | Ge 
           | Gt 
           | IndexPI 
           | LAnd 
           | LOr 
           | Le 
           | Lt 
           | MinusA 
           | MinusPI 
           | MinusPP 
           | Mod 
           | Mult 
           | Ne 
           | PlusA 
           | PlusPI 
           | Shiftlt 
           | Shiftrt 
           deriving ( Show)
-- Block -------------------------------------------------------
type Block = ( (CilAttributes),(Stmts))
-- CilAttribute ------------------------------------------------
data CilAttribute = Attr (String) (AttrParams)
                  deriving ( Show)
-- CilAttributes -----------------------------------------------
type CilAttributes = [(CilAttribute)]
-- CilFile -----------------------------------------------------
type CilFile = ( (String),(Globals),(OptFunDec),(Bool))
-- CilType -----------------------------------------------------
data CilType = TArray (CilType) (OptExp) (CilAttributes)
             | TBuiltinVas (CilAttributes)
             | TComp (CompInfo) (CilAttributes)
             | TEnum (EnumInfo) (CilAttributes)
             | TFloat (FloatKind) (CilAttributes)
             | TFun (CilType) (FormalArgs) (Bool) (CilAttributes)
             | TInt (IntKind) (CilAttributes)
             | TNamed (TypeInfo) (CilAttributes)
             | TPtr (CilType) (CilAttributes)
             | TVoid (CilAttributes)
             deriving ( Show)
-- Comment -----------------------------------------------------
type Comment = ( (Location),(String))
-- CompInfo ----------------------------------------------------
data CompInfo = CompInfo (Bool) (String) (Int) (FieldInfos) (CilAttributes) (Bool) (Bool)
              deriving ( Show)
-- Constant ----------------------------------------------------
data Constant = CChr (Char)
              | CEnum (Exp) (String) (EnumInfo)
              | CInt64 (Int64) (IntKind) ((Maybe String))
              | CReal (Float) (FloatKind) ((Maybe String))
              | CStr (String)
              | CWStr ([Int64])
              deriving ( Show)
-- EltInitializer ----------------------------------------------
type EltInitializer = ( (Offset),(Init))
-- EltInitializers ---------------------------------------------
type EltInitializers = [(EltInitializer)]
-- EnumInfo ----------------------------------------------------
data EnumInfo = EnumInfo (String) (Items) (CilAttributes) (Bool)
              deriving ( Show)
-- ExceptExp ---------------------------------------------------
type ExceptExp = ( (Instrs),(Exp))
-- Exp ---------------------------------------------------------
data Exp = AddrOf (Lval)
         | AlignOf (CilType)
         | AlignOfE (Exp)
         | BinOp (BinOp) (Exp) (Exp) (CilType)
         | CastE (CilType) (Exp)
         | Const (Constant)
         | Lval (Lval)
         | SizeOf (CilType)
         | SizeOfE (Exp)
         | SizeOfStr (String)
         | StartOf (Lval)
         | UnOp (UnOp) (Exp) (CilType)
         deriving ( Show)
-- Exps --------------------------------------------------------
type Exps = [(Exp)]
-- FieldInfo ---------------------------------------------------
data FieldInfo = FieldInfo (String) (CilType) ((Maybe Int)) (CilAttributes) (Location)
               deriving ( Show)
-- FieldInfos --------------------------------------------------
type FieldInfos = [(FieldInfo)]
-- FloatKind ---------------------------------------------------
data FloatKind = FDouble 
               | FFloat 
               | FLongDouble 
               deriving ( Show)
-- FormalArg ---------------------------------------------------
type FormalArg = ( (String),(CilType),(CilAttributes))
-- FormalArgs --------------------------------------------------
type FormalArgs = [(FormalArg)]
-- FunDec ------------------------------------------------------
data FunDec = FunDec (VarInfo) (VarInfos) (VarInfos) (Int) (Block) ((Maybe Int)) (Stmts)
            deriving ( Show)
-- Global ------------------------------------------------------
data Global = GAsm (String) (Location)
            | GCompTag (CompInfo) (Location)
            | GCompTagDecl (CompInfo) (Location)
            | GEnumTag (EnumInfo) (Location)
            | GEnumTagDecl (EnumInfo) (Location)
            | GFun (FunDec) (Location)
            | GPragma (CilAttribute) (Location)
            | GText (String)
            | GType (TypeInfo) (Location)
            | GVar (VarInfo) (InitInfo) (Location)
            | GVarDecl (VarInfo) (Location)
            deriving ( Show)
-- Globals -----------------------------------------------------
type Globals = [(Global)]
-- Init --------------------------------------------------------
data Init = CompoundInit (CilType) (EltInitializers)
          | SingleInit (Exp)
          deriving ( Show)
-- InitInfo ----------------------------------------------------
data InitInfo = InitInfo (OptInit)
              deriving ( Show)
-- Instr -------------------------------------------------------
data Instr = Asm (CilAttributes) ([String]) (AsmOutputs) (AsmInputs) ([String]) (Location)
           | Call (OptLval) (Exp) (Exps) (Location)
           | Set (Lval) (Exp) (Location)
           deriving ( Show)
-- Instrs ------------------------------------------------------
type Instrs = [(Instr)]
-- IntKind -----------------------------------------------------
data IntKind = IChar 
             | IInt 
             | ILong 
             | ILongLong 
             | ISChar 
             | IShort 
             | IUChar 
             | IUInt 
             | IULong 
             | IULongLong 
             | IUShort 
             deriving ( Show)
-- Item --------------------------------------------------------
type Item = ( (String),(Exp),(Location))
-- Items -------------------------------------------------------
type Items = [(Item)]
-- Label -------------------------------------------------------
data Label = Case (Exp) (Location)
           | Default (Location)
           | Label (String) (Location) (Bool)
           deriving ( Show)
-- Labels ------------------------------------------------------
type Labels = [(Label)]
-- Lhost -------------------------------------------------------
data Lhost = Mem (Exp)
           | Var (VarInfo)
           deriving ( Show)
-- Location ----------------------------------------------------
data Location = Location (Int) (String) (Int)
              deriving ( Show)
-- Lval --------------------------------------------------------
type Lval = ( (Lhost),(Offset))
-- Offset ------------------------------------------------------
data Offset = Field (FieldInfo) (Offset)
            | Index (Exp) (Offset)
            | NoOffset 
            deriving ( Show)
-- OptExp ------------------------------------------------------
type OptExp = (Maybe (Exp))
-- OptFunDec ---------------------------------------------------
type OptFunDec = (Maybe (FunDec))
-- OptInit -----------------------------------------------------
type OptInit = (Maybe (Init))
-- OptLval -----------------------------------------------------
type OptLval = (Maybe (Lval))
-- OptStmt -----------------------------------------------------
type OptStmt = (Maybe (Stmt))
-- OptVarInfo --------------------------------------------------
type OptVarInfo = (Maybe (VarInfo))
-- Stmt --------------------------------------------------------
data Stmt = Stmt (Labels) (StmtKind) (Int)
          deriving ( Show)
-- StmtKind ----------------------------------------------------
data StmtKind = Block (Block)
              | Break (Location)
              | Continue (Location)
              | Goto (Stmt) (Location)
              | If (Exp) (Block) (Block) (Location)
              | Instr (Instrs)
              | Loop (Block) (Location) (OptStmt) (OptStmt)
              | Return (OptExp) (Location)
              | Switch (Exp) (Block) (Stmts) (Location)
              | TryExcept (Block) (ExceptExp) (Block) (Location)
              | TryFinally (Block) (Block) (Location)
              deriving ( Show)
-- Stmts -------------------------------------------------------
type Stmts = [(Stmt)]
-- Storage -----------------------------------------------------
data Storage = Extern 
             | NoStorage 
             | Register 
             | Static 
             deriving ( Show)
-- TypeInfo ----------------------------------------------------
data TypeInfo = TypeInfo (String) (CilType) (Bool)
              deriving ( Show)
-- TypeSig -----------------------------------------------------
data TypeSig = TSArray (TypeSig) ((Maybe Int64)) (CilAttributes)
             | TSBase (CilType)
             | TSComp (Bool) (String) (CilAttributes)
             | TSEnum (String) (CilAttributes)
             | TSFun (TypeSig) (TypeSigs) (Bool) (CilAttributes)
             | TSPtr (TypeSig) (CilAttributes)
             deriving ( Show)
-- TypeSigs ----------------------------------------------------
type TypeSigs = [(TypeSig)]
-- UnOp --------------------------------------------------------
data UnOp = BNot 
          | LNot 
          | Neg 
          deriving ( Show)
-- VarInfo -----------------------------------------------------
data VarInfo = VarInfo (String) (CilType) (CilAttributes) (Storage) (Bool) (Bool) (Location) (Int) (Bool) (Bool)
             deriving ( Show)
-- VarInfos ----------------------------------------------------
type VarInfos = [(VarInfo)]


