{-# LANGUAGE CPP                        #-}
{-# OPTIONS -Wall #-}

--------------------------------------------------------------------------------
-- |
-- Module      :  Graphics.Rendering.OpenVG.Constants
-- Copyright   :  (c) Stephen Tetley 2008
-- License     :  BSD-style (see the LICENSE file in the distribution)
--
-- Maintainer  :  Stephen Tetley <stephen.tetley@gmail.com>
-- Stability   :  highly unstable
-- Portability :  GHC
--
-- This purely internal module defines the platform-specific stuff which has
-- been figured out by configure.
--
--------------------------------------------------------------------------------

module Graphics.Rendering.OpenVG.Constants where

import Graphics.Rendering.OpenVG.Config (VGboolean, VGenum)

--------------------------------------------------------------------------------

#include "HsOpenVGConfig.h"

--------------------------------------------------------------------------------

vg_FALSE, vg_TRUE :: VGboolean
vg_FALSE                            = CONST_VG_FALSE
vg_TRUE                             = CONST_VG_TRUE


--------------------------------------------------------------------------------

vg_MATRIX_MODE, vg_FILL_RULE, vg_IMAGE_QUALITY, vg_RENDERING_QUALITY,
    vg_BLEND_MODE, vg_IMAGE_MODE :: VGenum
vg_MATRIX_MODE                      = CONST_VG_MATRIX_MODE
vg_FILL_RULE                        = CONST_VG_FILL_RULE
vg_IMAGE_QUALITY                    = CONST_VG_IMAGE_QUALITY
vg_RENDERING_QUALITY                = CONST_VG_RENDERING_QUALITY
vg_BLEND_MODE                       = CONST_VG_BLEND_MODE
vg_IMAGE_MODE                       = CONST_VG_IMAGE_MODE

vg_SCISSOR_RECTS :: VGenum
vg_SCISSOR_RECTS                    = CONST_VG_SCISSOR_RECTS

vg_COLOR_TRANSFORM, vg_CONST_VG_COLOR_TRANSFORM_VALUES :: VGenum
vg_COLOR_TRANSFORM                  = CONST_VG_COLOR_TRANSFORM
vg_CONST_VG_COLOR_TRANSFORM_VALUES  = CONST_VG_COLOR_TRANSFORM_VALUES

vg_STROKE_LINE_WIDTH, vg_STROKE_CAP_STYLE, vg_STROKE_JOIN_STYLE, 
    vg_STROKE_MITER_LIMIT, vg_STROKE_DASH_PATTERN,
    vg_STROKE_DASH_PHASE, vg_STROKE_DASH_PHASE_RESET ::VGenum
vg_STROKE_LINE_WIDTH                = CONST_VG_STROKE_LINE_WIDTH
vg_STROKE_CAP_STYLE                 = CONST_VG_STROKE_CAP_STYLE
vg_STROKE_JOIN_STYLE                = CONST_VG_STROKE_JOIN_STYLE
vg_STROKE_MITER_LIMIT               = CONST_VG_STROKE_MITER_LIMIT
vg_STROKE_DASH_PATTERN              = CONST_VG_STROKE_DASH_PATTERN
vg_STROKE_DASH_PHASE                = CONST_VG_STROKE_DASH_PHASE
vg_STROKE_DASH_PHASE_RESET          = CONST_VG_STROKE_DASH_PHASE_RESET

vg_TILE_FILL_COLOR :: VGenum
vg_TILE_FILL_COLOR                  = CONST_VG_TILE_FILL_COLOR

vg_CLEAR_COLOR :: VGenum
vg_CLEAR_COLOR                      = CONST_VG_CLEAR_COLOR

vg_GLYPH_ORIGIN :: VGenum
vg_GLYPH_ORIGIN                     = CONST_VG_GLYPH_ORIGIN

vg_MASKING, vg_SCISSORING :: VGenum
vg_MASKING                          = CONST_VG_MASKING
vg_SCISSORING                       = CONST_VG_SCISSORING

vg_PIXEL_LAYOUT, vg_SCREEN_LAYOUT :: VGenum
vg_PIXEL_LAYOUT                     = CONST_VG_PIXEL_LAYOUT
vg_SCREEN_LAYOUT                    = CONST_VG_SCREEN_LAYOUT

vg_FILTER_FORMAT_LINEAR, vg_FILTER_FORMAT_PREMULTIPLIED :: VGenum
vg_FILTER_FORMAT_LINEAR             = CONST_VG_FILTER_FORMAT_LINEAR
vg_FILTER_FORMAT_PREMULTIPLIED      = CONST_VG_FILTER_FORMAT_PREMULTIPLIED

vg_FILTER_CHANNEL_MASK :: VGenum
vg_FILTER_CHANNEL_MASK              = CONST_VG_FILTER_CHANNEL_MASK

vg_MAX_SCISSOR_RECTS, vg_MAX_DASH_COUNT, vg_MAX_KERNEL_SIZE, 
    vg_MAX_SEPARABLE_KERNEL_SIZE, vg_MAX_COLOR_RAMP_STOPS, 
    vg_MAX_IMAGE_WIDTH, vg_MAX_IMAGE_HEIGHT, vg_MAX_IMAGE_PIXELS, 
    vg_MAX_IMAGE_BYTES, vg_MAX_FLOAT, vg_MAX_GAUSSIAN_STD_DEVIATION :: VGenum
vg_MAX_SCISSOR_RECTS                = CONST_VG_MAX_SCISSOR_RECTS
vg_MAX_DASH_COUNT                   = CONST_VG_MAX_DASH_COUNT
vg_MAX_KERNEL_SIZE                  = CONST_VG_MAX_KERNEL_SIZE
vg_MAX_SEPARABLE_KERNEL_SIZE        = CONST_VG_MAX_SEPARABLE_KERNEL_SIZE
vg_MAX_COLOR_RAMP_STOPS             = CONST_VG_MAX_COLOR_RAMP_STOPS
vg_MAX_IMAGE_WIDTH                  = CONST_VG_MAX_IMAGE_WIDTH
vg_MAX_IMAGE_HEIGHT                 = CONST_VG_MAX_IMAGE_HEIGHT
vg_MAX_IMAGE_PIXELS                 = CONST_VG_MAX_IMAGE_PIXELS
vg_MAX_IMAGE_BYTES                  = CONST_VG_MAX_IMAGE_BYTES
vg_MAX_FLOAT                        = CONST_VG_MAX_FLOAT
vg_MAX_GAUSSIAN_STD_DEVIATION       = CONST_VG_MAX_GAUSSIAN_STD_DEVIATION

--------------------------------------------------------------------------------
vg_RENDERING_QUALITY_NONANTIALIASED, vg_RENDERING_QUALITY_FASTER,
    vg_RENDERING_QUALITY_BETTER :: VGenum
vg_RENDERING_QUALITY_NONANTIALIASED = CONST_VG_RENDERING_QUALITY_NONANTIALIASED
vg_RENDERING_QUALITY_FASTER         = CONST_VG_RENDERING_QUALITY_FASTER
vg_RENDERING_QUALITY_BETTER         = CONST_VG_RENDERING_QUALITY_BETTER

vg_PIXEL_LAYOUT_UNKNOWN, 
    vg_PIXEL_LAYOUT_RGB_VERTICAL, vg_PIXEL_LAYOUT_BGR_VERTICAL,
    vg_PIXEL_LAYOUT_RGB_HORIZONTAL, vg_PIXEL_LAYOUT_BGR_HORIZONTAL :: VGenum
vg_PIXEL_LAYOUT_UNKNOWN             = CONST_VG_PIXEL_LAYOUT_UNKNOWN
vg_PIXEL_LAYOUT_RGB_VERTICAL        = CONST_VG_PIXEL_LAYOUT_RGB_VERTICAL
vg_PIXEL_LAYOUT_BGR_VERTICAL        = CONST_VG_PIXEL_LAYOUT_BGR_VERTICAL
vg_PIXEL_LAYOUT_RGB_HORIZONTAL      = CONST_VG_PIXEL_LAYOUT_RGB_HORIZONTAL
vg_PIXEL_LAYOUT_BGR_HORIZONTAL      = CONST_VG_PIXEL_LAYOUT_BGR_HORIZONTAL


vg_MATRIX_PATH_USER_TO_SURFACE, vg_MATRIX_IMAGE_USER_TO_SURFACE, 
    vg_MATRIX_FILL_PAINT_TO_USER, vg_MATRIX_STROKE_PAINT_TO_USER, 
    vg_MATRIX_GLYPH_USER_TO_SURFACE :: VGenum
vg_MATRIX_PATH_USER_TO_SURFACE      = CONST_VG_MATRIX_PATH_USER_TO_SURFACE
vg_MATRIX_IMAGE_USER_TO_SURFACE     = CONST_VG_MATRIX_IMAGE_USER_TO_SURFACE
vg_MATRIX_FILL_PAINT_TO_USER        = CONST_VG_MATRIX_FILL_PAINT_TO_USER
vg_MATRIX_STROKE_PAINT_TO_USER      = CONST_VG_MATRIX_STROKE_PAINT_TO_USER
vg_MATRIX_GLYPH_USER_TO_SURFACE     = CONST_VG_MATRIX_GLYPH_USER_TO_SURFACE



--------------------------------------------------------------------------------
vg_CLEAR_MASK, vg_FILL_MASK, vg_SET_MASK, vg_UNION_MASK, vg_INTERSECT_MASK, 
    vg_SUBTRACT_MASK :: VGenum 
vg_CLEAR_MASK                       = CONST_VG_CLEAR_MASK
vg_FILL_MASK                        = CONST_VG_FILL_MASK
vg_SET_MASK                         = CONST_VG_SET_MASK
vg_UNION_MASK                       = CONST_VG_UNION_MASK
vg_INTERSECT_MASK                   = CONST_VG_INTERSECT_MASK
vg_SUBTRACT_MASK                    = CONST_VG_SUBTRACT_MASK

--------------------------------------------------------------------------------

vg_PATH_CAPABILITY_APPEND_FROM, vg_PATH_CAPABILITY_APPEND_TO,
    vg_PATH_CAPABILITY_MODIFY, vg_PATH_CAPABILITY_TRANSFORM_FROM,
    vg_PATH_CAPABILITY_TRANSFORM_TO, vg_PATH_CAPABILITY_INTERPOLATE_FROM, 
    vg_PATH_CAPABILITY_INTERPOLATE_TO, vg_PATH_CAPABILITY_PATH_LENGTH, 
    vg_PATH_CAPABILITY_POINT_ALONG_PATH, vg_PATH_CAPABILITY_TANGENT_ALONG_PATH, 
    vg_PATH_CAPABILITY_PATH_BOUNDS, vg_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS,
    vg_PATH_CAPABILITY_ALL :: VGenum 
vg_PATH_CAPABILITY_APPEND_FROM              = CONST_VG_PATH_CAPABILITY_APPEND_FROM
vg_PATH_CAPABILITY_APPEND_TO                = CONST_VG_PATH_CAPABILITY_APPEND_TO
vg_PATH_CAPABILITY_MODIFY                   = CONST_VG_PATH_CAPABILITY_MODIFY
vg_PATH_CAPABILITY_TRANSFORM_FROM           = CONST_VG_PATH_CAPABILITY_TRANSFORM_FROM
vg_PATH_CAPABILITY_TRANSFORM_TO             = CONST_VG_PATH_CAPABILITY_TRANSFORM_TO
vg_PATH_CAPABILITY_INTERPOLATE_FROM         = CONST_VG_PATH_CAPABILITY_INTERPOLATE_FROM
vg_PATH_CAPABILITY_INTERPOLATE_TO           = CONST_VG_PATH_CAPABILITY_INTERPOLATE_TO
vg_PATH_CAPABILITY_PATH_LENGTH              = CONST_VG_PATH_CAPABILITY_PATH_LENGTH
vg_PATH_CAPABILITY_POINT_ALONG_PATH         = CONST_VG_PATH_CAPABILITY_POINT_ALONG_PATH
vg_PATH_CAPABILITY_TANGENT_ALONG_PATH       = CONST_VG_PATH_CAPABILITY_TANGENT_ALONG_PATH
vg_PATH_CAPABILITY_PATH_BOUNDS              = CONST_VG_PATH_CAPABILITY_PATH_BOUNDS
vg_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS  = CONST_VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS
vg_PATH_CAPABILITY_ALL                      = CONST_VG_PATH_CAPABILITY_ALL


vg_PATH_FORMAT, vg_PATH_DATATYPE, vg_PATH_SCALE, vg_PATH_BIAS, 
    vg_PATH_NUM_SEGMENTS, vg_PATH_NUM_COORDS :: VGenum
vg_PATH_FORMAT                      = CONST_VG_PATH_FORMAT
vg_PATH_DATATYPE                    = CONST_VG_PATH_DATATYPE
vg_PATH_SCALE                       = CONST_VG_PATH_SCALE
vg_PATH_BIAS                        = CONST_VG_PATH_BIAS
vg_PATH_NUM_SEGMENTS                = CONST_VG_PATH_NUM_SEGMENTS
vg_PATH_NUM_COORDS                  = CONST_VG_PATH_NUM_COORDS

vg_CAP_BUTT, vg_CAP_ROUND, vg_CAP_SQUARE :: VGenum
vg_CAP_BUTT                         = CONST_VG_CAP_BUTT
vg_CAP_ROUND                        = CONST_VG_CAP_ROUND
vg_CAP_SQUARE                       = CONST_VG_CAP_SQUARE

vg_JOIN_MITER, vg_JOIN_ROUND, vg_JOIN_BEVEL :: VGenum
vg_JOIN_MITER                       = CONST_VG_JOIN_MITER
vg_JOIN_ROUND                       = CONST_VG_JOIN_ROUND
vg_JOIN_BEVEL                       = CONST_VG_JOIN_BEVEL

vg_EVEN_ODD, vg_NON_ZERO :: VGenum 
vg_EVEN_ODD                         = CONST_VG_EVEN_ODD
vg_NON_ZERO                         = CONST_VG_NON_ZERO

vg_STROKE_PATH, vg_FILL_PATH :: VGenum
vg_STROKE_PATH                      = CONST_VG_STROKE_PATH 
vg_FILL_PATH                        = CONST_VG_FILL_PATH

--------------------------------------------------------------------------------
vg_RED, vg_GREEN, vg_BLUE, vg_ALPHA :: VGenum
vg_RED                              = CONST_VG_RED
vg_GREEN                            = CONST_VG_GREEN
vg_BLUE                             = CONST_VG_BLUE
vg_ALPHA                            = CONST_VG_ALPHA

--------------------------------------------------------------------------------
vg_PAINT_TYPE, vg_PAINT_COLOR, vg_PAINT_COLOR_RAMP_SPREAD_MODE, 
    vg_PAINT_COLOR_RAMP_STOPS, vg_PAINT_COLOR_RAMP_PREMULTIPLIED, 
    vg_PAINT_LINEAR_GRADIENT, vg_PAINT_RADIAL_GRADIENT, 
    vg_PAINT_PATTERN_TILING_MODE :: VGenum

vg_PAINT_TYPE                       = CONST_VG_PAINT_TYPE
vg_PAINT_COLOR                      = CONST_VG_PAINT_COLOR
vg_PAINT_COLOR_RAMP_SPREAD_MODE     = CONST_VG_PAINT_COLOR_RAMP_SPREAD_MODE
vg_PAINT_COLOR_RAMP_STOPS           = CONST_VG_PAINT_COLOR_RAMP_STOPS
vg_PAINT_COLOR_RAMP_PREMULTIPLIED   = CONST_VG_PAINT_COLOR_RAMP_PREMULTIPLIED
vg_PAINT_LINEAR_GRADIENT            = CONST_VG_PAINT_LINEAR_GRADIENT
vg_PAINT_RADIAL_GRADIENT            = CONST_VG_PAINT_RADIAL_GRADIENT
vg_PAINT_PATTERN_TILING_MODE        = CONST_VG_PAINT_PATTERN_TILING_MODE

vg_PAINT_TYPE_COLOR, vg_PAINT_TYPE_LINEAR_GRADIENT, 
    vg_PAINT_TYPE_RADIAL_GRADIENT, vg_PAINT_TYPE_PATTERN :: VGenum
vg_PAINT_TYPE_COLOR                 = CONST_VG_PAINT_TYPE_COLOR
vg_PAINT_TYPE_LINEAR_GRADIENT       = CONST_VG_PAINT_TYPE_LINEAR_GRADIENT
vg_PAINT_TYPE_RADIAL_GRADIENT       = CONST_VG_PAINT_TYPE_RADIAL_GRADIENT
vg_PAINT_TYPE_PATTERN               = CONST_VG_PAINT_TYPE_PATTERN


vg_COLOR_RAMP_SPREAD_PAD, vg_COLOR_RAMP_SPREAD_REPEAT, 
    vg_COLOR_RAMP_SPREAD_REFLECT :: VGenum
vg_COLOR_RAMP_SPREAD_PAD            = CONST_VG_COLOR_RAMP_SPREAD_PAD
vg_COLOR_RAMP_SPREAD_REPEAT         = CONST_VG_COLOR_RAMP_SPREAD_REPEAT
vg_COLOR_RAMP_SPREAD_REFLECT        = CONST_VG_COLOR_RAMP_SPREAD_REFLECT

vg_TILE_FILL, vg_TILE_PAD, vg_TILE_REPEAT, vg_TILE_REFLECT :: VGenum
vg_TILE_FILL                        = CONST_VG_TILE_FILL
vg_TILE_PAD                         = CONST_VG_TILE_PAD
vg_TILE_REPEAT                      = CONST_VG_TILE_REPEAT
vg_TILE_REFLECT                     = CONST_VG_TILE_REFLECT


--------------------------------------------------------------------------------
vg_IMAGE_QUALITY_NONANTIALIASED, vg_IMAGE_QUALITY_FASTER, 
    vg_IMAGE_QUALITY_BETTER :: VGenum
vg_IMAGE_QUALITY_NONANTIALIASED     = CONST_VG_IMAGE_QUALITY_NONANTIALIASED
vg_IMAGE_QUALITY_FASTER             = CONST_VG_IMAGE_QUALITY_FASTER
vg_IMAGE_QUALITY_BETTER             = CONST_VG_IMAGE_QUALITY_BETTER

vg_IMAGE_FORMAT, vg_IMAGE_WIDTH, vg_IMAGE_HEIGHT :: VGenum
vg_IMAGE_FORMAT                     = CONST_VG_IMAGE_FORMAT
vg_IMAGE_WIDTH                      = CONST_VG_IMAGE_WIDTH
vg_IMAGE_HEIGHT                     = CONST_VG_IMAGE_HEIGHT

vg_DRAW_IMAGE_NORMAL, vg_DRAW_IMAGE_MULTIPLY, vg_DRAW_IMAGE_STENCIL :: VGenum
vg_DRAW_IMAGE_NORMAL                = CONST_VG_DRAW_IMAGE_NORMAL
vg_DRAW_IMAGE_MULTIPLY              = CONST_VG_DRAW_IMAGE_MULTIPLY
vg_DRAW_IMAGE_STENCIL               = CONST_VG_DRAW_IMAGE_STENCIL


--------------------------------------------------------------------------------
vg_BLEND_SRC, vg_BLEND_SRC_OVER, vg_BLEND_DST_OVER, 
    vg_BLEND_SRC_IN, vg_BLEND_DST_IN, vg_BLEND_MULTIPLY, 
    vg_BLEND_SCREEN, vg_BLEND_DARKEN, vg_BLEND_LIGHTEN, 
    vg_BLEND_ADDITIVE :: VGenum
vg_BLEND_SRC                        = CONST_VG_BLEND_SRC
vg_BLEND_SRC_OVER                   = CONST_VG_BLEND_SRC_OVER
vg_BLEND_DST_OVER                   = CONST_VG_BLEND_DST_OVER
vg_BLEND_SRC_IN                     = CONST_VG_BLEND_SRC_IN
vg_BLEND_DST_IN                     = CONST_VG_BLEND_DST_IN
vg_BLEND_MULTIPLY                   = CONST_VG_BLEND_MULTIPLY
vg_BLEND_SCREEN                     = CONST_VG_BLEND_SCREEN
vg_BLEND_DARKEN                     = CONST_VG_BLEND_DARKEN
vg_BLEND_LIGHTEN                    = CONST_VG_BLEND_LIGHTEN
vg_BLEND_ADDITIVE                   = CONST_VG_BLEND_ADDITIVE

--------------------------------------------------------------------------------
vg_IMAGE_FORMAT_QUERY, vg_PATH_DATATYPE_QUERY :: VGenum
vg_IMAGE_FORMAT_QUERY               = CONST_VG_IMAGE_FORMAT_QUERY
vg_PATH_DATATYPE_QUERY              = CONST_VG_PATH_DATATYPE_QUERY

vg_HARDWARE_ACCELERATED, vg_HARDWARE_UNACCELERATED :: VGenum
vg_HARDWARE_ACCELERATED             = CONST_VG_HARDWARE_ACCELERATED
vg_HARDWARE_UNACCELERATED           = CONST_VG_HARDWARE_UNACCELERATED

--------------------------------------------------------------------------------

vg_ID_VENDOR, vg_ID_RENDERER, vg_ID_VERSION, vg_ID_EXTENSIONS :: VGenum
vg_ID_VENDOR                        = CONST_VG_VENDOR
vg_ID_RENDERER                      = CONST_VG_RENDERER 
vg_ID_VERSION                       = CONST_VG_VERSION 
vg_ID_EXTENSIONS                    = CONST_VG_EXTENSIONS

--------------------------------------------------------------------------------

vg_FONT_NUM_GLYPHS :: VGenum
vg_FONT_NUM_GLYPHS                  = CONST_VG_FONT_NUM_GLYPHS

