/* For the time being this is a hand-coded stub */



#define CONST_VG_FALSE 0
#define CONST_VG_TRUE 0


#define HTYPE_VGENUM Word32


#define CONST_VG_MATRIX_MODE       0x1100
#define CONST_VG_MATRIX_MODE       0x1100
#define CONST_VG_FILL_RULE         0x1101
#define CONST_VG_IMAGE_QUALITY     0x1102
#define CONST_VG_RENDERING_QUALITY 0x1103
#define CONST_VG_BLEND_MODE        0x1104
#define CONST_VG_IMAGE_MODE        0x1105

#define CONST_VG_SCISSOR_RECTS	  0x1106

#define CONST_VG_COLOR_TRANSFORM  0x1170
#define CONST_VG_COLOR_TRANSFORM_VALUES 0x1171

#define CONST_VG_STROKE_LINE_WIDTH  0x1110
#define CONST_VG_STROKE_CAP_STYLE   0x1111
#define CONST_VG_STROKE_JOIN_STYLE  0x1112
#define CONST_VG_STROKE_MITER_LIMIT 0x1113
#define CONST_VG_STROKE_DASH_PATTERN 0x1114
#define CONST_VG_STROKE_DASH_PHASE  0x1115
#define CONST_VG_STROKE_DASH_PHASE_RESET 0x1116

#define CONST_VG_TILE_FILL_COLOR 0x1120

#define CONST_VG_CLEAR_COLOR 0x1121

#define CONST_VG_GLYPH_ORIGIN 0x1122

#define CONST_VG_MASKING 0x1130
#define CONST_VG_SCISSORING 0x1131

#define CONST_VG_PIXEL_LAYOUT 0x1140
#define CONST_VG_SCREEN_LAYOUT 0x1141

#define CONST_VG_FILTER_FORMAT_LINEAR 0x1150
#define CONST_VG_FILTER_FORMAT_PREMULTIPLIED 0x1151

#define CONST_VG_FILTER_CHANNEL_MASK 0x1152

#define CONST_VG_MAX_SCISSOR_RECTS          0x1160
#define CONST_VG_MAX_DASH_COUNT             0x1161
#define CONST_VG_MAX_KERNEL_SIZE            0x1162
#define CONST_VG_MAX_SEPARABLE_KERNEL_SIZE  0x1163
#define CONST_VG_MAX_COLOR_RAMP_STOPS       0x1164
#define CONST_VG_MAX_IMAGE_WIDTH            0x1165
#define CONST_VG_MAX_IMAGE_HEIGHT           0x1166
#define CONST_VG_MAX_IMAGE_PIXELS           0x1167
#define CONST_VG_MAX_IMAGE_BYTES            0x1168
#define CONST_VG_MAX_FLOAT                  0x1169
#define CONST_VG_MAX_GAUSSIAN_STD_DEVIATION 0x116A

#define CONST_VG_RENDERING_QUALITY_NONANTIALIASED 	0x1200
#define CONST_VG_RENDERING_QUALITY_FASTER           0x1201
#define CONST_VG_RENDERING_QUALITY_BETTER           0x1202

#define CONST_VG_PIXEL_LAYOUT_UNKNOWN        0x1300
#define CONST_VG_PIXEL_LAYOUT_RGB_VERTICAL   0x1301
#define CONST_VG_PIXEL_LAYOUT_BGR_VERTICAL   0x1302
#define CONST_VG_PIXEL_LAYOUT_RGB_HORIZONTAL 0x1303
#define CONST_VG_PIXEL_LAYOUT_BGR_HORIZONTAL 0x1304

#define CONST_VG_MATRIX_PATH_USER_TO_SURFACE  0x1400
#define CONST_VG_MATRIX_IMAGE_USER_TO_SURFACE 0x1401
#define CONST_VG_MATRIX_FILL_PAINT_TO_USER    0x1402
#define CONST_VG_MATRIX_STROKE_PAINT_TO_USER  0x1403
#define CONST_VG_MATRIX_GLYPH_USER_TO_SURFACE 0x1404


#define CONST_VG_CLEAR_MASK     0x1500
#define CONST_VG_FILL_MASK      0x1501
#define CONST_VG_SET_MASK       0x1502
#define CONST_VG_UNION_MASK     0x1503
#define CONST_VG_INTERSECT_MASK 0x1504
#define CONST_VG_SUBTRACT_MASK  0x1505

#warning
#define CONST_VG_PATH_CAPABILITY_APPEND_FROM      0
#define CONST_VG_PATH_CAPABILITY_APPEND_TO        1
#define CONST_VG_PATH_CAPABILITY_MODIFY           2
#define CONST_VG_PATH_CAPABILITY_TRANSFORM_FROM   3
#define CONST_VG_PATH_CAPABILITY_TRANSFORM_TO     4
#define CONST_VG_PATH_CAPABILITY_INTERPOLATE_FROM 5
#define CONST_VG_PATH_CAPABILITY_INTERPOLATE_TO   6
#define CONST_VG_PATH_CAPABILITY_PATH_LENGTH      7
#define CONST_VG_PATH_CAPABILITY_POINT_ALONG_PATH 8
#define CONST_VG_PATH_CAPABILITY_TANGENT_ALONG_PATH 9
#define CONST_VG_PATH_CAPABILITY_PATH_BOUNDS      10
#define CONST_VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS 11
#define CONST_VG_PATH_CAPABILITY_ALL              12


#define CONST_VG_PATH_FORMAT       0x1600
#define CONST_VG_PATH_DATATYPE     0x1601
#define CONST_VG_PATH_SCALE        0x1602
#define CONST_VG_PATH_BIAS         0x1603
#define CONST_VG_PATH_NUM_SEGMENTS 0x1604
#define CONST_VG_PATH_NUM_COORDS   0x1605


#define CONST_VG_CAP_BUTT   0x1700
#define CONST_VG_CAP_ROUND  0x1701
#define CONST_VG_CAP_SQUARE 0x1702

#define CONST_VG_JOIN_MITER 0x1800
#define CONST_VG_JOIN_ROUND 0x1801
#define CONST_VG_JOIN_BEVEL 0x1802

#define CONST_VG_EVEN_ODD   0x1900
#define CONST_VG_NON_ZERO   0x1901

#warning
#define CONST_VG_STROKE_PATH  1 
#define CONST_VG_FILL_PATH    2


#warning
#define CONST_VG_RED   3
#define CONST_VG_GREEN 2
#define CONST_VG_BLUE  1
#define CONST_VG_ALPHA 0

#define CONST_VG_PAINT_TYPE    0x1A00
#define CONST_VG_PAINT_COLOR   0x1A01
#define CONST_VG_PAINT_COLOR_RAMP_SPREAD_MODE   0x1A02
#define CONST_VG_PAINT_COLOR_RAMP_STOPS         0x1A03
#define CONST_VG_PAINT_COLOR_RAMP_PREMULTIPLIED 0x1A07
/* Linear gradient paint parameters */
#define CONST_VG_PAINT_LINEAR_GRADIENT   0x1A04
/* Radial gradient paint parameters */
#define CONST_VG_PAINT_RADIAL_GRADIENT   0x1A05
/* Pattern paint parameters */
#define CONST_VG_PAINT_PATTERN_TILING_MODE 0x1A06


#define CONST_VG_BLEND_SRC 			0x2000
#define CONST_VG_BLEND_SRC_OVER 	0x2001
#define CONST_VG_BLEND_DST_OVER 	0x2002
#define CONST_VG_BLEND_SRC_IN 		0x2003
#define CONST_VG_BLEND_DST_IN 		0x2004
#define CONST_VG_BLEND_MULTIPLY 	0x2005
#define CONST_VG_BLEND_SCREEN 		0x2006
#define CONST_VG_BLEND_DARKEN 		0x2007
#define CONST_VG_BLEND_LIGHTEN 		0x2008
#define CONST_VG_BLEND_ADDITIVE 	0x2009

#define CONST_VG_IMAGE_FORMAT_QUERY  0x2100
#define CONST_VG_PATH_DATATYPE_QUERY 0x2101

#define CONST_VG_HARDWARE_ACCELERATED   0x2200
#define CONST_VG_HARDWARE_UNACCELERATED 0x2201


#define CONST_VG_VENDOR		0x2300
#define CONST_VG_RENDERER 	0x2301
#define CONST_VG_VERSION 	0x2302
#define CONST_VG_EXTENSIONS 0x2303


#define CONST_VG_FONT_NUM_GLYPHS 0x2F00

